baseurl: ""  # The subpath of your site, e.g. /blog
url: "http://yourwebsite.com"  # Base hostname & protocol

markdown: kramdown
permalink: /:lang/:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

languages:
  - en
  - es

collections:
  pages:
    output: true
    permalink: /:lang/:name

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: "en"  # Default language

sass:
  sass_dir: _sass
  style: compressed

i18n:
  default_lang: "en"
